import { expect, test } from "@playwright/test"

test("first login requires an unclosable password change before administration", async ({ page }) => {
  await page.goto("/login")
  await expect(page.getByText("Use the initial password configured in")).toBeVisible()
  await page.getByLabel("Password", { exact: true }).fill("e2e-initial-password")
  await page.getByRole("button", { name: "Sign in", exact: true }).click()
  const dialog = page.getByRole("dialog")
  await expect(dialog).toContainText("Set a private admin password")
  expect((await page.request.get("/api/admin/workspaces")).status()).toBe(403)
  await expect(dialog.getByRole("button", { name: "Close", exact: true })).toHaveCount(0)
  await page.keyboard.press("Escape")
  await expect(dialog).toBeVisible()
  await page.mouse.click(5, 5)
  await expect(dialog).toBeVisible()
  await page.reload()
  await expect(dialog).toBeVisible()
  const inputs = dialog.locator('input[type="password"]')
  await inputs.nth(0).fill("private-password")
  await inputs.nth(1).fill("wrong-confirmation")
  await dialog.getByRole("button", { name: "Change password", exact: true }).click()
  await expect(page.getByText("New passwords do not match.", { exact: true })).toBeVisible()
  await expect(dialog).toBeVisible()
  await inputs.nth(1).fill("private-password")
  await dialog.getByRole("button", { name: "Change password", exact: true }).click()
  await expect(dialog).toBeHidden()
  await expect(page.getByRole("button", { name: "Create key", exact: true })).toBeVisible()
  await page.request.post("/api/auth/logout")
  await page.goto("/login")
  await expect(page.getByText(/Initial password:|Use the initial password configured in/)).toHaveCount(0)
  expect((await page.request.post("/api/auth/login", { data: { password: "e2e-initial-password" } })).status()).toBe(401)
})

test("local login renders the documented default hint, while remote login hides it", async ({ page }) => {
  await page.route("**/api/auth/bootstrap", route => route.fulfill({ json: { isDefaultPassword: true, defaultPasswordHint: "change-me-now" } }))
  await page.goto("/login")
  await expect(page.getByText("Initial password:")).toContainText("change-me-now")
  await page.route("http://remote.rawroute.test/**", async route => {
    const url = new URL(route.request().url())
    const response = await route.fetch({ url: `http://127.0.0.1:3100${url.pathname}${url.search}` })
    await route.fulfill({ response })
  })
  await page.goto("http://remote.rawroute.test/login")
  await expect(page.getByRole("button", { name: "Sign in", exact: true })).toBeEnabled()
  await expect(page.getByText(/Initial password:|Use the initial password configured in/)).toHaveCount(0)
})
