import { closeLocalDatabase, listLocalDocuments, upsertLocalDocuments } from "@/lib/local-db"
import { startOfZonedDay } from "@/lib/timezone"
import type { UsageRollup } from "@/lib/types"

/**
 * Repairs aggregate-only backfills when a higher-resolution source covers the
 * exact same request segment. The current known case is the CCS Aug 6 bucket:
 * its hourly rows came from the keyed SQLite request history, while its daily
 * rows were generated by an inconsistent Firestore aggregate.
 *
 * The equality check is intentional. If the hourly source is partial, it is
 * not safe to replace a daily aggregate with it; the report leaves that row
 * untouched for manual/source reconciliation instead of guessing.
 */

type LocalDocument = Awaited<ReturnType<typeof listLocalDocuments>>[number]
type NumericRollup = {
  requests: number
  inputTokens: number
  outputTokens: number
  cacheReadTokens: number
  cacheCreationTokens: number
  totalTokens: number
  costMicros: number
  pricedRequests: number
  unpricedRequests: number
  lastEventAt?: string
}

const apply = process.argv.includes("--apply")
const ccsSource = "ccs-usage-v2"

function isRollupCollection(value: string) {
  return value.endsWith("_usage_rollups") || value.endsWith("/usageRollups")
}

function number(value: unknown) {
  const parsed = Number(value)
  return Number.isFinite(parsed) ? parsed : 0
}

function rollupValue(data: Record<string, unknown>): NumericRollup {
  return {
    requests: Math.max(0, Math.round(number(data.requests))),
    inputTokens: Math.max(0, Math.round(number(data.inputTokens))),
    outputTokens: Math.max(0, Math.round(number(data.outputTokens))),
    cacheReadTokens: Math.max(0, Math.round(number(data.cacheReadTokens))),
    cacheCreationTokens: Math.max(0, Math.round(number(data.cacheCreationTokens))),
    totalTokens: Math.max(0, Math.round(number(data.totalTokens))),
    costMicros: Math.max(0, Math.round(number(data.costMicros))),
    pricedRequests: Math.max(0, Math.round(number(data.pricedRequests))),
    unpricedRequests: Math.max(0, Math.round(number(data.unpricedRequests))),
    lastEventAt: typeof data.lastEventAt === "string" ? data.lastEventAt : undefined,
  }
}

function add(left: NumericRollup | undefined, right: NumericRollup) {
  const current = left || {
    requests: 0, inputTokens: 0, outputTokens: 0, cacheReadTokens: 0,
    cacheCreationTokens: 0, totalTokens: 0, costMicros: 0, pricedRequests: 0,
    unpricedRequests: 0,
  }
  return {
    requests: current.requests + right.requests,
    inputTokens: current.inputTokens + right.inputTokens,
    outputTokens: current.outputTokens + right.outputTokens,
    cacheReadTokens: current.cacheReadTokens + right.cacheReadTokens,
    cacheCreationTokens: current.cacheCreationTokens + right.cacheCreationTokens,
    totalTokens: current.totalTokens + right.totalTokens,
    costMicros: current.costMicros + right.costMicros,
    pricedRequests: current.pricedRequests + right.pricedRequests,
    unpricedRequests: current.unpricedRequests + right.unpricedRequests,
    lastEventAt: !current.lastEventAt || (right.lastEventAt && right.lastEventAt > current.lastEventAt)
      ? right.lastEventAt
      : current.lastEventAt,
  } satisfies NumericRollup
}

function keyFor(document: LocalDocument, data: Record<string, unknown>, bucketStart: string) {
  return [
    document.collection_path,
    bucketStart,
    data.gatewayKeyId || "",
    data.gatewayModelId || "",
  ].join("\u0000")
}

function equalValues(left: NumericRollup, right: NumericRollup) {
  return [
    "requests", "inputTokens", "outputTokens", "cacheReadTokens", "cacheCreationTokens",
    "totalTokens", "costMicros", "pricedRequests", "unpricedRequests",
  ].every((field) => left[field as keyof NumericRollup] === right[field as keyof NumericRollup])
}

async function main() {
  const documents = await listLocalDocuments()
  const rollups = documents.filter((document) => isRollupCollection(document.collection_path))
  const hourly = new Map<string, NumericRollup>()
  for (const document of rollups) {
    const data = document.data
    if (data.backfillSource !== ccsSource || data.granularity !== "hourly" || typeof data.bucketStart !== "string") continue
    const bucketStart = startOfZonedDay(new Date(data.bucketStart)).toISOString()
    const key = keyFor(document, data, bucketStart)
    hourly.set(key, add(hourly.get(key), rollupValue(data)))
  }

  const repairs: Array<{ path: string; data: UsageRollup; before: NumericRollup; after: NumericRollup; bucketStart: string }> = []
  for (const document of rollups) {
    const data = document.data
    if (data.backfillSource !== ccsSource || data.granularity !== "daily" || typeof data.bucketStart !== "string") continue
    const after = hourly.get(keyFor(document, data, data.bucketStart))
    if (!after) continue
    const before = rollupValue(data)
    // A matching request count proves that the higher-resolution rows cover
    // the same aggregate segment. Token/cost differences are exactly what is
    // being repaired, so do not require those values to match.
    if (before.requests === 0 || before.requests !== after.requests || equalValues(before, after)) continue
    const next: UsageRollup = {
      ...(data as unknown as UsageRollup),
      ...after,
      id: typeof data.id === "string" ? data.id : document.document_id,
      granularity: "daily",
      bucketStart: data.bucketStart,
      gatewayKeyId: String(data.gatewayKeyId || ""),
      gatewayModelId: String(data.gatewayModelId || ""),
      updatedAt: new Date().toISOString(),
      reconciledFrom: "ccs-usage-v2-hourly",
    }
    repairs.push({ path: document.path, data: next, before, after, bucketStart: data.bucketStart })
  }

  if (apply && repairs.length) await upsertLocalDocuments(repairs.map((repair) => ({ path: repair.path, data: repair.data })))
  const totalBefore = repairs.reduce((sum, repair) => sum + repair.before.costMicros, 0)
  const totalAfter = repairs.reduce((sum, repair) => sum + repair.after.costMicros, 0)
  console.log(JSON.stringify({
    mode: apply ? "apply" : "dry-run",
    source: ccsSource,
    candidates: repairs.length,
    repaired: apply ? repairs.length : 0,
    costBeforeMicros: totalBefore,
    costAfterMicros: totalAfter,
    costDeltaMicros: totalAfter - totalBefore,
    costBeforeUsd: totalBefore / 1_000_000,
    costAfterUsd: totalAfter / 1_000_000,
    rows: repairs.map((repair) => ({
      path: repair.path,
      bucketStart: repair.bucketStart,
      requests: repair.after.requests,
      costBeforeUsd: repair.before.costMicros / 1_000_000,
      costAfterUsd: repair.after.costMicros / 1_000_000,
    })),
  }, null, 2))
}

void main().catch((error) => {
  console.error(error instanceof Error ? error.message : error)
  process.exitCode = 1
}).finally(() => closeLocalDatabase())
