// Stable server event names and messages. Never construct messages from request data.
export const serverEvents = {
  "cliproxy.lifecycle": { message: "CLIProxy lifecycle event", source: "cliproxy" },
  "auth.login.rejected": { message: "Admin login rejected", source: "auth" },
  "auth.login.succeeded": { message: "Admin signed in", source: "auth" },
  "auth.logout": { message: "Admin signed out", source: "auth" },
  "admin.cliproxy.setting.update.failed": { message: "CLIProxy setting update failed", source: "admin" },
  "admin.cliproxy.settings.updated": { message: "CLIProxy settings updated", source: "admin" },
  "admin.cliproxy.settings.update.failed": { message: "CLIProxy settings update failed", source: "admin" },
  "admin.model.pricing.groups.synced": { message: "Model pricing groups synced", source: "admin" },
  "admin.model.pricing.group.created": { message: "Model pricing group created", source: "admin" },
  "admin.model.pricing.group.updated": { message: "Model pricing group updated", source: "admin" },
  "admin.model.pricing.group.deleted": { message: "Model pricing group deleted", source: "admin" },
  "admin.model.pricing.version.saved": { message: "Model pricing version saved", source: "admin" },
  "admin.model.pricing.update.failed": { message: "Model pricing update failed", source: "admin" },
  "workspace.created": { message: "Workspace created", source: "admin" },
  "admin.workspace.create.failed": { message: "Workspace create failed", source: "admin" },
  "workspace.renamed": { message: "Workspace renamed", source: "admin" },
  "admin.workspace.rename.failed": { message: "Workspace rename failed", source: "admin" },
  "workspace.deleted": { message: "Workspace deleted", source: "admin" },
  "admin.workspace.delete.failed": { message: "Workspace delete failed", source: "admin" },
  "admin.alias.saved": { message: "Alias saved", source: "admin" },
  "admin.alias.save.failed": { message: "Alias save failed", source: "admin" },
  "admin.alias.deleted": { message: "Alias deleted", source: "admin" },
  "admin.alias.delete.failed": { message: "Alias delete failed", source: "admin" },
  "auth.password.changed": { message: "Password updated", source: "admin" },
  "auth.password.failed": { message: "Password update failed", source: "admin" },
  "admin.gateway.api.key.renamed": { message: "Gateway API key renamed", source: "admin" },
  "admin.gateway.api.key.rename.failed": { message: "Gateway API key rename failed", source: "admin" },
  "admin.gateway.api.key.deleted": { message: "Gateway API key deleted", source: "admin" },
  "admin.gateway.api.key.delete.failed": { message: "Gateway API key delete failed", source: "admin" },
  "admin.gateway.api.key.created": { message: "Gateway API key created", source: "admin" },
  "admin.gateway.api.key.create.failed": { message: "Gateway API key create failed", source: "admin" },
  "admin.budget.saved": { message: "Budget saved", source: "admin" },
  "admin.budget.save.failed": { message: "Budget save failed", source: "admin" },
  "admin.budget.deleted": { message: "Budget deleted", source: "admin" },
  "admin.budget.delete.failed": { message: "Budget delete failed", source: "admin" },
  "admin.budget.window.updated": { message: "Budget window updated", source: "admin" },
  "admin.budget.window.update.failed": { message: "Budget window update failed", source: "admin" },
  "admin.unlimited.mode.exclusions.updated": { message: "Unlimited Mode exclusions updated", source: "admin" },
  "admin.unlimited.mode.exclusions.update.failed": { message: "Unlimited Mode exclusions update failed", source: "admin" },
  "admin.beyond.limits.settings.updated": { message: "Beyond Limits settings updated", source: "admin" },
  "admin.beyond.limits.settings.update.failed": { message: "Beyond Limits settings update failed", source: "admin" },
  "admin.unlimited.mode.updated": { message: "Unlimited Mode updated", source: "admin" },
  "admin.unlimited.mode.update.failed": { message: "Unlimited Mode update failed", source: "admin" },
  "admin.model.sharing.updated": { message: "Model sharing updated", source: "admin" },
  "admin.model.sharing.update.failed": { message: "Model sharing update failed", source: "admin" },
  "admin.cliproxy.oauth.login.started": { message: "CLIProxy OAuth login started", source: "admin" },
  "admin.cliproxy.oauth.login.cancelled": { message: "CLIProxy OAuth login cancelled", source: "admin" },
  "admin.cliproxy.authentication.record.deleted": { message: "CLIProxy authentication record deleted", source: "admin" },
  "admin.cliproxy.authentication.record.updated": { message: "CLIProxy authentication record updated", source: "admin" },
  "admin.cliproxy.api.key.update.failed": { message: "CLIProxy API key update failed", source: "admin" },
  "admin.cliproxy.logs.cleared": { message: "CLIProxy logs cleared", source: "admin" },
  "admin.combo.deleted": { message: "Combo deleted", source: "admin" },
  "admin.combo.delete.failed": { message: "Combo delete failed", source: "admin" },
  "admin.combo.saved": { message: "Combo saved", source: "admin" },
  "admin.combo.save.failed": { message: "Combo save failed", source: "admin" },
  "admin.provider.saved": { message: "Provider saved", source: "admin" },
  "admin.provider.save.failed": { message: "Provider save failed", source: "admin" },
  "admin.provider.api.key.deleted": { message: "Provider API key deleted", source: "admin" },
  "admin.provider.api.key.delete.failed": { message: "Provider API key delete failed", source: "admin" },
  "admin.provider.api.key.saved": { message: "Provider API key saved", source: "admin" },
  "admin.provider.api.key.save.failed": { message: "Provider API key save failed", source: "admin" },
  "admin.provider.api.keys.reordered": { message: "Provider API keys reordered", source: "admin" },
  "admin.provider.api.key.reorder.failed": { message: "Provider API key reorder failed", source: "admin" },
  "admin.model.deleted": { message: "Model deleted", source: "admin" },
  "admin.model.delete.failed": { message: "Model delete failed", source: "admin" },
  "admin.model.saved": { message: "Model saved", source: "admin" },
  "admin.model.save.failed": { message: "Model save failed", source: "admin" },
  "admin.provider.deleted": { message: "Provider deleted", source: "admin" },
  "admin.provider.delete.failed": { message: "Provider delete failed", source: "admin" },
  "admin.codex.reset.credit.redemption.failed": { message: "Codex reset credit redemption failed", source: "admin" },
  "admin.codex.account.updated": { message: "Codex account updated", source: "admin" },
  "admin.codex.account.update.failed": { message: "Codex account update failed", source: "admin" },
  "admin.codex.account.deleted": { message: "Codex account deleted", source: "admin" },
  "admin.codex.account.delete.failed": { message: "Codex account delete failed", source: "admin" },
  "admin.cliproxy.codex.login.started": { message: "CLIProxy Codex login started", source: "admin" },
  "admin.cliproxy.codex.login.start.failed": { message: "CLIProxy Codex login start failed", source: "admin" },
  "admin.cliproxy.codex.account.mapped": { message: "CLIProxy Codex account mapped", source: "admin" },
  "admin.cliproxy.codex.login.failed": { message: "CLIProxy Codex login failed", source: "admin" },
  "http.request.failed": { message: "HTTP request failed", source: "system" },
  "system.unable.to.warm.usage.prediction.history": { message: "Unable to warm usage prediction history", source: "system" },
  "admin.unlimited.mode.auto.deactivated.at.budget.window.end": { message: "Unlimited Mode auto-deactivated at budget window end", source: "admin" },
  "admin.unable.to.sync.codex.budget.window": { message: "Unable to sync Codex budget window", source: "admin" },
  "gateway.codex.quota.recovery.unavailable": { message: "Codex quota recovery unavailable", source: "gateway" },
  "gateway.codex.quota.available.allowing.inference.probe": { message: "Codex quota available; allowing inference probe", source: "gateway" },
  "gateway.codex.quota.recovery.check.failed": { message: "Codex quota recovery check failed", source: "gateway" },
  "admin.codex.reset.credit.redeemed": { message: "Codex reset credit redeemed", source: "admin" },
  "gateway.authentication.rejected": { message: "Request rejected: invalid API key", source: "gateway" },
  "gateway.unable.to.release.routing.lease": { message: "Unable to release routing lease", source: "gateway" },
  "gateway.combo.member.policy.is.invalid": { message: "Combo member policy is invalid", source: "gateway" },
  "gateway.combo.member.failed.trying.next": { message: "Combo member failed, trying next", source: "gateway" },
  "gateway.model.resolution.failed": { message: "Model resolution failed", source: "gateway" },
  "gateway.budget.state.unavailable": { message: "Budget state unavailable", source: "gateway" },
  "gateway.budget.admission.denied": { message: "Budget admission denied", source: "gateway" },
  "gateway.shared.budget.state.unavailable": { message: "Shared budget state unavailable", source: "gateway" },
  "gateway.upstream.request.failed": { message: "Upstream request failed", source: "gateway" },
  "gateway.unable.to.persist.usage.event": { message: "Unable to persist usage event", source: "gateway" },
  "gateway.unable.to.calculate.usage.event": { message: "Unable to calculate usage event", source: "gateway" },
  "admin.cliproxy.provider.projection.reconciled": { message: "CLIProxy provider projection reconciled", source: "admin" },
  "background.failed": { message: "Background task failed", source: "system" },
  "gateway.executor.authentication.is.unavailable": { message: "Executor authentication is unavailable", source: "gateway" },
  "gateway.executor.request.rejected.invalid.api.key": { message: "Executor request rejected: invalid API key", source: "gateway" },
  "gateway.executor.request.rejected.invalid.path": { message: "Executor request rejected: invalid path", source: "gateway" },
  "gateway.executor.proxy.is.not.configured": { message: "Executor proxy is not configured", source: "gateway" },
  "gateway.executor.upstream.request.failed": { message: "Executor upstream request failed", source: "gateway" },
  "gateway.request.started": { message: "Gateway request started", source: "gateway" },
  "gateway.request.completed": { message: "Gateway request completed", source: "gateway" },
  "gateway.request.failed": { message: "Gateway request failed", source: "gateway" },
  "http.request.completed": { message: "API request completed", source: "http" },
  "http.request.rejected": { message: "API request rejected", source: "http" },
  "system.started": { message: "RawRoute started", source: "system" },
  "system.stopping": { message: "RawRoute shutdown started", source: "system" },
  "system.stopped": { message: "RawRoute shutdown completed", source: "system" },
  "system.shutdown.failed": { message: "RawRoute shutdown failed", source: "system" },
  "logs.cleared": { message: "Log history cleared", source: "console" },
  "admin.cliproxy.keys.updated": { message: "CLIProxy API keys updated", source: "admin" },
  "admin.cliproxy.keys.failed": { message: "CLIProxy API key update failed", source: "admin" },
  "gateway.executor.response.received": { message: "Executor response headers received", source: "gateway" },
  "gateway.catalog.served": { message: "Gateway model catalog served", source: "gateway" },
  "gateway.budget.model.excluded": { message: "Model excluded by budget policy", source: "gateway" },
  "gateway.budget.pricing.unavailable": { message: "Budget pricing unavailable", source: "gateway" },
} as const

export type ServerEvent = keyof typeof serverEvents
